apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
  {{- include "postgres-prod.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: postgres-pod
  {{- include "postgres-prod.selectorLabels" . | nindent 4 }}
  ports:
    - port: 5432
      targetPort: 5432	
