package sh.logfire.flink.filter

object Constants {
  final val FLINK_CLUSTER_HOST = "FLINK_CLUSTER_HOST"
  final val FLINK_CLUSTER_PORT = "FLINK_CLUSTER_HOST"
  final val KAFKA_BROKERS = "KAFKA_BROKERS"
  final val SCHEMA_REGISTRY_ADDRESS = "SCHEMA_REGISTRY_ADDRESS"
  final val SEVERITY_LEVEL_FIELD = "SEVERITY_LEVEL_FIELD"
  final val MESSAGE_FIELD = "MESSAGE_FIELD"
}
