apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: prod-ingress
  labels:
  {{- include "ingress-prodchart.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - host: api.logfire.sh
    http:
      paths:
      - backend:
          service:
            name: hello
            port:
              number: 80
        path: /
        pathType: Prefix
      - backend:
          service:
            name: livetail
            port:
              number: 80
        path: /livetail(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: filterservice
            port:
              number: 80
        path: /logfilter(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: api-gateway-dapr
            port:
              number: 80
        path: /dapr(/|$)(.*)
        pathType: Prefix
      - backend:
          service:
            name: gowebapi
            port:
              number: 8080
        path: /api(/|$)(.*)
        pathType: Prefix
  tls:
  - hosts:
    - api.logfire.sh
    secretName: api-logfire-prod-tls-secret
